### ISSUE TITLE
Error Code 0.

### ISSUE THREAD

**Issue by weloveblackman22** [BobbyWibowo/lolisafe#470]
Whenever I upload a file ( over 200MB ) lolisafe responds with error code 0 and no logs in the console. I am using Cloudflare can someone explain and/or help me?

**Comment by BobbyWibowo** [comment]
Did you turn on chunked uploads?
Free plan of Cloudflare by default has an upload limit of 100MB
Lolisafe cannot detect your Cloudflare plan, so it's at your own discretion to turn on chunked uploads, and configure the max chunk size to match your plan
If you're on free plan, make max chunk size at 95MB at most (instead of flat 100MB), as it needs a bit of the bandwidth to send auxiliary data

**Comment by weloveblackman22** [comment]
Yes, i have enabled chunks now there's a new error ` An unexpected error occurred. Try again? ` . Theres this error that pops up in console to `[2022-04-21 16:47:35] Uncaught Exception: Error: Cannot continue updating hashing after dispose() has been called
    at BaseHash.update (/root/lolisafe/node_modules/blake3/dist/base/hash-instance.js:18:19)
    at NodeHash.update (/root/lolisafe/node_modules/blake3/dist/node/hash-instance.js:27:19)
    at FileStream.<anonymous> (/root/lolisafe/controllers/utils/multerStorage.js:70:40)
    at FileStream.emit (node:events:527:28)
    at FileStream.Readable.read (node:internal/streams/readable:550:10)
    at flow (node:internal/streams/readable:1034:34)
    at resume_ (node:internal/streams/readable:1015:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-04-21 16:47:35] [Error: ENOTSUP: operation not supported on socket, open '/lolisafestore/chunks/82aa0331-a5ef-4f6f-8fb3-d98ffa7b8787/tmp'] {
  errno: -95,
  code: 'ENOTSUP',
  syscall: 'open',
  path: '/lolisafestore/chunks/82aa0331-a5ef-4f6f-8fb3-d98ffa7b8787/tmp',
  storageErrors: []`

**Comment by BobbyWibowo** [comment]
Are you using a network drive as your uploads directory?
If yes, modify uploads > chunksFolder in config file to a local path, since building chunks isn't simple read/write operations, and may not be supported by certain network drive drivers
Lolisafe will automatically move the finished file / rebuilt chunks into your uploads directory afterwards

**Comment by weloveblackman22** [comment]
That was the problem thanks for helping!

**Comment by BobbyWibowo** [comment]
Anytime!
